### PR TITLE
Prefab/hello-libs:  for prefab debugging, do not merge

### PR DESCRIPTION
**Pull request by alexcohn**
use prefab for hello-libs

### CODE REVIEW

**Comment by ggfan** [comment]
thank you for the Pull Request!  I will have a look later: given that there is one sample already, and the other one from danalbert@ is inside Pull Request, this one probably is not an urgent one.  The uniqueness is about the generating the lib part, I think. Let me know you think  otherwise!

**Comment by alexcohn** [comment]
> The uniqueness is about the generating the lib part

That's true; also, the important message is to use **Prefab** for consuming external libs, whenever possible.

But actually, this sample is intended to triage some features of Prefab (e.g. reusing library bundle for prefab).

**Comment by ggfan** [comment]
this is to replicate issue:  https://b.corp.google.com/issues/120166563

**Comment by ggfan** [comment]
https://issuetracker.google.com/issues/120166563 is under implementation, let's follow it up there.
thank you for creating the test case.

**Pull request closed without merging**
