### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sheikzayed**
Typo in the readme file.

### CODE REVIEW

**Review by sheikzayed — COMMENTED** [review]
Readme file typo

**Comment by ggfan** [comment]
it says that you might need to get CLA signed: https://cla.developers.google.com,  may you follow up for that?  thx for the PR

**Comment by sheikzayed** [comment]
> it says that you might need to get CLA signed: https://cla.developers.google.com, may you follow up for that? thx for the PR

I have now signed CLA.

**Comment by sheikzayed** [comment]
i have now signed CLA

**Pull request merged**
