### PR TITLE
Usability improvements for hello-vulkan sample

### PR DESCRIPTION
**Pull request by kocdemir**
- Move member functions to a cpp file
- Remove redundant functions and calls
- Report validation layer messages to logcat
- Auto-disable validation layers when not found
- Feature support checks to avoid validation failures Extra logging to help with debugging when using the app

### CODE REVIEW

**Comment by kocdemir** [comment]
@DanAlbert @GOOG-sergiu

**Review by GOOG-sergiu — APPROVED** [review]
LGTM

**Comment by DanAlbert** [comment]
> Move member functions to a cpp file

Combining this with the other changes has made this more or less impossible to review, because github shows _every_ line as changed. Could you please split this into multiple PRs?

**Comment by kocdemir** [comment]
sure, will upload 2 PRs, thanks.

**Pull request closed without merging**
